### ISSUE TITLE
Microsoft Clarity not capturing full-page screenshots when using custom scrollbars

### ISSUE THREAD

**Issue by davidnagyworldofbooks** [microsoft/clarity#878]
We are currently integrating Clarity into our project and have encountered an issue where Clarity only captures the top portion of the page in its screenshots.

Our web application uses a custom scrollbar, implemented via a custom <div> that scrolls content internally (not the native body scroll).

How can we make Clarity recognize and track a custom scrollable container instead of the default window scroll?
If there is currently no support for this, could a feature be added to allow specifying a custom scroll container?

**Comment by SP5D** [comment]
Let me bump the issue.
For my layout Clarity makes screenshot of the first `100vh` only. It can't scroll anything(?) except <body>.
To be clear, here's an example of what my layout looks like. It's pretty standard:
```css
html,
body {
    height: 100%;
}
#scroll-container {
    height: 100vh;
    width: 100vw;
    overflow-y: scroll;
    overflow-x: hidden;
}
section {
    position: relative;
}
```
```html
<body>
<div id="scroll-container">
    <section>Long content...</section>
    <section>Long content...</section>
    <section>Long content...</section>
    // There are c.a. 20 sections. Sections are the only direct children of the #scroll-container
    // Most of the sections are above 100vh itself.
</div>
</body>
```
Nothing unusual, but a specific example (even a trivial one) is IMHO better and clearer than a description.
